modLoader = "javafml"
loaderVersion = "[14,)"
updateJSONURL = "https://raw.githubusercontent.com/TheRandomLabs/VanillaDeathChest/misc/versions.json"
issueTrackerURL = "https://github.com/TheRandomLabs/VanillaDeathChest/issues"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/vanilladeathchest"
logoFile = "logo.png"
authors = "TheRandomLabs"

[[mods]]

modId = "vanilladeathchest"
version = "${file.jarVersion}"
displayName = "VanillaDeathChest"
description = '''
VanillaDeathChest, a mod that places chests (or shulker boxes) where players die that contain all of their items.
'''
